export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const FETCH_CART= "FETCH_CART";
export const FETCH_ORDERS_LIST = "FETCH_ORDERS_LIST";
export const INSERT_PROMO_CODE = "INSERT_PROMO_CODE";
export const CREATE_ORDER = "CREATE_ORDER";
